name: fitness_nutrition
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_slidable: ^3.0.0
  flutter_bloc: ^8.1.4
  fl_chart: ^0.60.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  bloc: ^8.1.3
  percent_indicator: ^4.2.3
  equatable: ^2.0.3
  flutter_tts: ^3.8.1
  smooth_page_indicator: ^1.1.0
  formz: ^0.6.0
  intl: ^0.19.0
  get_it: ^7.6.0
  sembast: ^3.4.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^21.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true
  assets: 
    - assets/images/cbum.png
    - assets/images/dumbbell.png
    - assets/images/health.png
    - assets/images/yoga.png
    - assets/images/calisthenics.png
    - assets/images/cardio.png
    - assets/images/user.png
    - assets/images/woman_1.jpg
    - assets/images/woman_2.jpg
    - assets/images/woman_3.jpg
    - assets/images/woman_4.jpg
    - assets/images/woman_5.jpg
    - assets/images/woman_6.jpg
    - assets/images/woman_6.jpg
    - assets/images/man_1.jpg
    - assets/images/man_2.jpg
    - assets/images/man_3.jpg
    - assets/images/man_4.jpg
    - assets/images/man_5.jpg
    - assets/images/man_6.jpg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppin/Poppins-Regular.otf
        - asset: assets/fonts/poppin/Poppins-Light.otf
        - asset: assets/fonts/poppin/Poppins-Medium.otf
        - asset: assets/fonts/poppin/Poppins-Bold.otf
    - family: TimeNewRoman
      fonts:
        - asset: assets/fonts/TimesNewRoman/TimesNr-Bold.ttf
        - asset: assets/fonts/TimesNewRoman/TimesNr-BoldItalic.ttf
        - asset: assets/fonts/TimesNewRoman/TimesNr-Italic.ttf
        - asset: assets/fonts/TimesNewRoman/TimesNr-Medium.ttf
        - asset: assets/fonts/TimesNewRoman/TimesNr-MediumItalic.ttf
        - asset: assets/fonts/TimesNewRoman/TimesNr-Regular.ttf
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant/Cormorant-Bold.ttf
        - asset: assets/fonts/Cormorant/Cormorant-BoldItalic.ttf
        - asset: assets/fonts/Cormorant/Cormorant-Italic.ttf
        - asset: assets/fonts/Cormorant/Cormorant-Light.ttf
        - asset: assets/fonts/Cormorant/Cormorant-LightItalic.ttf
        - asset: assets/fonts/Cormorant/Cormorant-Medium.ttf
        - asset: assets/fonts/Cormorant/Cormorant-MediumItalic.ttf
        - asset: assets/fonts/Cormorant/Cormorant-Regular.ttf
        - asset: assets/fonts/Cormorant/Cormorant-SemiBold.ttf
        - asset: assets/fonts/Cormorant/Cormorant-SemiBoldItalic.ttf

  